config/routes.rb
Rails.application.routes.draw do

   root 'elementos#index'
   resources 'elementos'

end

app/models/elemento.rb
class Elemento < ActiveRecord::Base
	
end

app/models/elemnto.rb
class Elemnto < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/elementos_controller.rb
class ElementosController < ApplicationController

	def index
		@elementos = Elemento.page(params[:page]).per(6)
	end


	def new
	  @elemento = Elemento.new
	end

	def create
	  @elemento = Elemento.new(elemento_params)

	  if @elemento.save
	    flash[:notice] = "Inserido com sucesso no banco..."
	    redirect_to @elemento

	  else
	   	flash[:notice] = "Não pode ser inserido no banco..."
	   	render new
	  end		
	end

	def show
		@elemento = Elemento.find(params[:id])
		
	end


	def update
		
	end

	def destroy
		
	end

	private 

	def elemento_params
		params.require(:elemento).permit(:alcunha, :crime, :nome, :cidade_atuacao, :condenado,
			           :motivo_condenacao, :responde_crime, :motivo_responde, :estado_atuacao,
			           :pai, :mae, :idade, :observacao)
	
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elementos_helper.rb
module ElementosHelper
end

app/views/elementos/_form.html.erb
<h2>Inserir</h2>

<%= form_for(@elemento) do |f| %>
 <% if @elemento.errors.any? %>
 <div id="error_explanation" >
 	<h2><%= pluralize(@elemento.errors.count, "error")  %>
 		Problemas ao executar esta acao	</h2>


 	<ul> 
 		<% elemento.errors.full_menssages_each do |msg| %>
 		<li><%= msg %></li>
 	<% end %>
 	</ul>
 </div>
<% end %>


<div class="col-lg-12 col-sm-12 hero-feature">
					<table class="table table-bordered tbl-checkout">
						<tbody>
                            <tr>
                                <td>Nome</td>
                                <td>
                                    <%= f.text_field :nome , :class=> "form-control"%>
                                </td>
                                <td>Alcunha</td>
                                <td>
                                	<%= f.text_field :alcunha , :class=> "form-control"%> 
                                    
                                </td>
                            </tr>
                            <tr>
                                <td>Crimes</td>
                                <td>
									<%= f.text_field :crime , :class=> "form-control"%> 
                                <td>Idade</td>
                                <td>
                                    <%= f.text_field :idade , :class=> "form-control"%> 
                                </td>
                            </tr>
                            
                            <tr>
                                <td>Estado Atuação</td>
                                <td>
                                    <%= f.text_field :estado_atuacao , :class=> "form-control"%> 
                                </td>

                                <td>Cidades Atuação</td>
                                <td>
                                    <%= f.text_field :cidade_atuacao , :class=> "form-control"%> 
                                </td>
                             <tr>   
                                <td>Condenado</td>
                                <td>
                                    <%= f.text_field :condenado , :class=> "form-control"%> 
                                </td>

                                <td>Motivo condenação</td>
                                <td>
                                    <%= f.text_field :motivo_condenacao , :class=> "form-control"%> 
                                </td>
                            </tr>

                            <tr>   
                                <td>Responde</td>
                                <td>
                                    <%= f.text_field :responde_crime , :class=> "form-control"%> 
                                </td>

                                <td>Motivo-Respode</td>
                                <td>
                                    <%= f.text_field :motivo_responde , :class=> "form-control"%> 
                                </td>
                            </tr>

                            <tr>   
                                <td>Mãe</td>
                                <td>
                                    <%= f.text_field :mae , :class=> "form-control"%> 
                                </td>

                                <td>Pai</td>
                                <td>
                                    <%= f.text_field :pai , :class=> "form-control"%> 
                                </td>
                            </tr>


                            <tr>
                                <td>Country</td>
                                <td>
                                    <select class="form-control">
                                        <option value=""> --- Please Select --- </option>
                                        <option value="244">Aaland Islands</option>
                                      </select>
                                </td>
                                <td class="tujuan">Region / State:</td>
                                <td class="jne">
                                    <select class="form-control"><option value=""> --- Please Select --- </option><option value="3513">Aberdeen</option><option value="3514">Aberdeenshire</option><option value="3515">Anglesey</option><</select>
                                </td>
                            </tr>
                            <tr>
                                <td>Observação</td>
                                <td colspan="3">
                                    <%= f.text_area :observacao , :class=> "form-control"%> 
                                </td>
                            </tr>

                            <tr>
                                <td>Address</td>
                                <td colspan="3">
                                    <textarea name="" class="form-control"></textarea>
                                </td>
                            </tr>

                        </tbody>
					</table>
                    
					<div class="btn-group btns-cart">
						<%= f.submit " Inserir dados ", :class => "btn btn-primary" %>
						<% end %>	
						
					</div>

	            </div>

	            

app/views/elementos/index.html.erb
  
  

        	<div class="clearfix visible-sm"></div>

			<!-- Featured -->
        	<div class="col-lg-9 col-md-9 col-sm-12">
        		<div class="col-lg-12 col-sm-12">
            		<span class="title">
            			<% flash.each do |key , value| %>
							<div class= 'flash' id='<% key %>' >
								<%= value %>
							</div>	
						<% end %>	
            		</span>
            	</div>
            	
            	<% @elementos.each do |elemento| %>

	            <div class="col-lg-4 col-sm-4 hero-feature text-center">
	                <div class="thumbnail">
	                	<a href="detail.html" class="link-p">
	                    	<%= image_tag("2.jpg") %>
	                	</a>
	                    <div class="caption prod-caption">
	                        <h5><a <%= link_to elemento.alcunha, elemento %></a>
	                         


	                        <p><%= elemento.crime %></p>
	                        <p>
	                        	<div class="btn-group">
		                        	<%= link_to elemento, :class=>"btn btn-primary"  do %>
										<i class="fa fa-eye"> ver  </i>
									<% end %>


		                        		

	                        	</div>
	                        </p>
	                    </div>
	                </div>
	            </div>
	            
	            <% end %>
        	<!-- End Featured -->
               
        	<div class="text-center">
        		<%= paginate @elementos , :outer_window => 6 %>
		    </div>
			<div class="clearfix visible-sm"></div>

			

 </div>

app/views/elementos/new.html.erb
<%= render "form" %>

app/views/elementos/show.html.erb
<center><h3>Relatório</h3></center>


<div class="col-lg-4 col-sm-4 hero-feature text-center">
                    <div class="thumbnail">
                        <a href="detail.html" class="link-p">
                            <%= image_tag("2.jpg") %>
                        </a>
                        
                    </div>
                </div>
                <div class="col-lg-4 col-sm-4 hero-feature text-center">
                    <div class="thumbnail">
                        <a href="detail.html" class="link-p">
                           <%= image_tag("2.jpg") %>
                        </a>
                        
                    </div>
                </div>
                <div class="col-lg-4 col-sm-4 hero-feature text-center">
                    <div class="thumbnail">
                        <a href="detail.html" class="link-p">
                            <%= image_tag("2.jpg") %>
                        </a>
                        
                    </div>
                </div>

<table class="table table-bordered tbl-cart">
    <thead>
        <tr>
            <td>Nome</td>
            <td>Alcunha</td>
            <td>Idade</td>
            <td>Crimes</td>
            <td>Estado-Atucão</td>
            <td>Cidade-Atuação</td>
            
        </tr>
    </thead>
        <tbody>
            <tr>
                <td><%= @elemento.nome %></td>
                <td><%= @elemento.alcunha %></td>
                <td><%= @elemento.idade %></td>
                <td><%= @elemento.crime %></td>
                <td><%= @elemento.estado_atuacao %></td>
                <td><%= @elemento.cidade_atuacao %></td>
                
            </tr>
        </tbody>
</table>

<table class="table table-bordered tbl-cart">
     <thead>
        <tr>
            <td>Condenação</td>
            <td>Acusação</td>
            <td>Condenado</td>
            <td>Respode outro crime</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><%= @elemento.condenado %></td>
            <td><%= @elemento.responde_crime %></td>
            <td><%= @elemento.motivo_condenacao %></td>
            <td><%= @elemento.motivo_responde %></td>
        </tr>                            
    </tbody>                        
</table>

<table class="table table-bordered tbl-cart">
     <thead>
        <tr>
            <td>Mãe</td>
            <td>Pai</td>
            
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><%= @elemento.mae %></td>
            <td><%= @elemento.pai %></td>
        </tr>                            
    </tbody>                        
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home - Fotos</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
	<header>
	    <div class="container">
	        <div class="row">

	        	<!-- Logo -->
	            <div class="col-lg-4 col-md-3 hidden-sm hidden-xs">
	            	<div class="well logo">
	            		<a href="index.html">
	            			Idenficação <span>Online</span>
	            		</a>

	            		<!--<div>Vim, vi, venci.</div> -->
	            	</div>
	            </div>
	            <!-- End Logo -->

				<!-- Search Form -->
	            <div class="col-lg-5 col-md-5 col-sm-7 col-xs-12">
	            	<div class="well">
	                    <form action="">
	                        <div class="input-group">
	                            <input type="text" class="form-control input-search" placeholder="Digite o Texto de Busca"/>
	                            <span class="input-group-btn">
	                                <button class="btn btn-default no-border-left" type="submit"><i class="fa fa-search"></i></button>
	                            </span>
	                        </div>
	                    </form>
	                </div>
	            </div>
	            <!-- End Search Form -->

	            <!-- Shopping Cart List -->
	            <div class="col-lg-3 col-md-4 col-sm-5">
	                <div class="well">
	                    <div class="btn-group btn-group-cart">
	                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                <span class="pull-left"><i class="fa fa-user"></i></span>
                                <span class="pull-left">-Ações</span>
                                <span class="pull-right"><i class="fa fa-caret-down"></i></span>
                            </button>
                            <ul class="dropdown-menu cart-content" role="menu">
                                <li>
                                    <a href="detail.html">
                                        <b>Sair</b>
                                    </a>
                                </li>
                                <li>
                                    <a href="detail.html">
                                        <b>ação2</b>   
                                    </a>
                                </li>

                                <li>
                                    <a href="detail.html">
                                        <b>ação2</b>   
                                    </a>
                                </li>
                                
                            </ul>
	                    </div>
	                </div>
	            </div>
	            <!-- End Shopping Cart List -->
	        </div>
	    </div>
    </header>

	<!-- Navigation -->
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- text logo on mobile view -->
                <a class="navbar-brand visible-xs" href="index.html">identificacao</a>
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li> <%= link_to "Home", elementos_path %> </a></li>
                    <li><a href="cart.html">Busca Avaçada</a></li></li>
                    <li><a <%= link_to "Inserir", new_elemento_path  %> </a></li>
                    <li><a href="catalogue.html">Index</a></li>
                    <li><a href="cart.html">Busca Avaçada</a></li>
                    <li><a href="checkout.html">Cadastro</a></li>

                    <li class="nav-dropdown">
                    	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Pages <span class="caret"></span>
						</a>
						<ul class="dropdown-menu">
							<li><a href="about.html">About Us</a></li>
							<li><a href="contact.html">Contact Us</a></li>
							<li><a href="typography.html">Typography</a></li>
						</ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- End Navigation -->
    <div class="container main-container">    
        <%= yield %>
    </div>    


	<footer>
    	<div class="container">
        	<div class="col-lg-3 col-md-3 col-sm-6">
        		<div class="column">
        			<h4>Information</h4>
        			<ul>
        				<li><a href="about.html">About Us</a></li>
        				<li><a href="typography.html">Policy Privacy</a></li>
        				<li><a href="typography.html">Terms and Conditions</a></li>
        				<li><a href="typography.html">Shipping Methods</a></li>
        			</ul>
        		</div>
        	</div>
        	<div class="col-lg-3 col-md-3 col-sm-6">
        		<div class="column">
        			<h4>Categories</h4>
        			<ul>
        				<li><a href="catalogue.html">Cras justo odio</a></li>
        				<li><a href="catalogue.html">Dapibus ac facilisis in</a></li>
        				<li><a href="catalogue.html">Morbi leo risus</a></li>
        				<li><a href="catalogue.html">Porta ac consectetur ac</a></li>
        			</ul>
        		</div>
        	</div>
        	<div class="col-lg-3 col-md-3 col-sm-6">
        		<div class="column">
        			<h4>Customer Service</h4>
        			<ul>
        				<li><a href="contact.html">Contact Us</a></li>
        				<li><a href="#">YM: erwin_heldy</a></li>
        				<li><a href="#">Telp: 087825376xxx</a></li>
        				<li><a href="#">Email: erwin.heldy@gmail.com</a></li>
        			</ul>
        		</div>
        	</div>
        	<div class="col-lg-3 col-md-3 col-sm-6">
        		<div class="column">
        			<h4>Follow Us</h4>
        			<ul class="social">
        				<li><a href="#">Google Plus</a></li>
        				<li><a href="#">Facebook</a></li>
        				<li><a href="#">Twitter</a></li>
        				<li><a href="#">RSS Feed</a></li>
        			</ul>
        		</div>
        	</div>
        </div>
        <div class="navbar-inverse text-center copyright">
        	Copyright &copy; SSP/NÚCLEO DE INTELIGÊNCIA - PCPI
        </div>
    </footer>

    <a href="#top" class="back-top text-center" onclick="$('body,html').animate({scrollTop:0},500); return false">
    	<i class="fa fa-angle-double-up"></i>
    </a>
</body>
</html>